version: '3.7'
services:
 web1:
  image: sbm782/django-test:1.3
  ports:
    - "8000:8000"
  networks:
    - default
    - test_net
 web2:
  image: sbm782/testnginx:1.0
  ports:
    - "4000:80"
  networks:
    - test_net
 database:
  image: redis
  networks:
    - test_net
  command: docker-compose exec web1 ping database
networks:
  test_net:
    driver: bridge
